apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hextris
  labels:
    app: hextris
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: hextris
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hextris
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: hextris
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: hextris
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
