apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hextris
spec:
  rules:
    - host: hextris.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hextris
                port:
                  number: 80
