pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kubectl
    image: israa2000/jenkins-agent-kubectl-helm:latest
    command:
    - cat
    tty: true
"""
            defaultContainer 'kubectl'
        }
    }
    stages {
        stage('Deploy with Helm') {
            steps {
                container('kubectl') {
                    script {
                        sh '''
                          set -e
                          echo "Starting Helm deployment..."
                          helm upgrade --install hextris ./helm-chart --namespace hextris --create-namespace || {
                              echo "❌ Helm failed: likely due to missing RBAC permissions on secrets in namespace 'hextris'."
                              exit 1
                          }
                        '''
                    }
                }
            }
    }
}
